/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "A cluster of palm trees, ripe for harvest": "一簇棕榈树，成熟等待收获",
    "A small but comfortable place to rest": "一个小而舒适的休息场所",
    "A vast, empty expanse": "广阔而空旷的地方",
    "Blocks sand from reaching up to 1 tiles behind it": "阻止沙子到达其后面最多 1 格的范围",
    "Cactus": "仙人掌",
    "Campsite": "露营地",
    "Contains space for": "包含空间用于",
    "Jobs": "工作",
    "Lonely and tall, a valuable source of fruit": "孤独又高大，是果实的宝贵来源",
    "Must be within 2 tiles of Water": "必须位于水的 2 格范围内",
    "Paused": "已暂停",
    "Provides a source of Civilization": "提供文明源泉",
    "Resources": "资源",
    "Sand": "沙",
    "Settle": "定居",
    "Soft and fertile, perfect for plants to thrive": "柔软肥沃，非常适合植物茁壮成长",
    "Soil": "土壤",
    "Supports 1 Builder": "支持 1 名建造者",
    "Supports 1 Forager": "支持 1 名采集者",
    "Supports 1 Scavenger": "支持1个拾荒者",
    "The Modding Tree\n                            Discord": "模组树\n Discord",
    "The Oasis": "绿洲",
    "The skies are clear. A light breeze blows over the oasis": "天空晴朗。 微风吹过绿洲",
    "Tree": "树",
    "Unemployed": "未分配",
    "Your people look for a place to settle down": "你的人民正在寻找安身之所",
    "A small pit dug in the sand. Some small stones can be found poking out": "沙子里挖了一个小坑。 可以发现一些小石头伸出来",
    "Brings 1 resource per day to building sites": "每天为建筑工地带来 1 种资源",
    "Builder": "建设者",
    "Cancel Construction": "取消施工",
    "Contains space for 3 People, 30 Food": "可容纳 3 人、30 种食物",
    "Cut down the Trees": "砍伐树木",
    "Demolish the Campsite": "拆除露营地",
    "Dig out a Sand Pit": "挖一个沙坑",
    "Food": "食物",
    "Forager": "采集者",
    "Build a Campsite": "正在进行中：建造一个露营地",
    "Lifegiving waters": "赋予生命的水域",
    "Main\n                Prestige Tree server": "主\n 声望树服务器",
    "Map": "地图",
    "Normal": "普通",
    "Oasis": "绿洲",
    "People": "人口",
    "Provides a source of Water": "提供水源",
    "Remaining Resources:": "剩余资源：",
    "Sand Pit": "沙坑",
    "Scavenger": "拾荒者",
    "Spent resources will be lost": "消耗的资源将会丢失",
    "Supports 1 Knapper": "支持 1 名碎石者",
    "Will help with sand removal duties": "将帮助清除沙子",
    "Will Require:": "将需要：",
    "Wood": "木头",
    "Cut down the Cactus": "砍掉仙人掌",
    "Fast": "快",
    "Fastest": "最快",
    "Must be within 2 tiles of Civilization": "必须位于文明 2 格以内",
    "Dig out a Sand Pit": "挖一个沙坑",
    "A strong breeze has picked up sand from the south, casting shade over the oasis": "一阵强风卷起了南方的沙子，给绿洲投下阴影",
    "The skies are clear": "天空晴朗",
    "Fill in the Sand Pit": "填满沙坑",
    "Knapper": "碎石者",
    "Sandstone": "砂岩",
    "A semi-permanent encampment": "半永久性营地",
    "Build an Encampment": "建立营地",
    "Contains space for 5 People, 50 Food": "可容纳 5 人、50 种食物",
    "Encampment": "营地",
    "Supports 2 Builders, 1 Crafter": "支持 2 名建造者、1 名工匠",
    "Upgrade to an Encampment": "升级到营地",
    "A dust storm hangs over the oasis, blotting out the sun and bringing sand in from the north": "沙尘暴笼罩着绿洲，遮挡了阳光，并从北方带来了沙子",
    "A large open hole in the ground, providing precious construction materials": "地面上的一个大洞，提供珍贵的建筑材料",
    "A small, permanent settlement": "一个小型的永久定居点",
    "Build a Settlement": "建立定居点",
    "build anew on the remains of the old": "在旧的遗迹上重建",
    "Consumption: 1 Wood, 1 Sandstone": "消耗：1 木材、1 砂岩",
    "Contains space for 15 People, 150 Food": "可容纳 15 人、150 份食物",
    "Crafter": "工匠",
    "Demolish the Encampment": "拆除营地",
    "Dig out a Quarry": "挖出一个采石场",
    "Fill in the Quarry": "填充采石场",
    "Let the sands sweep away the past,": "任凭流沙卷走往事，",
    "Miner": "矿工",
    "Quarry": "采石场",
    "Settlement": "定居点",
    "Stone Tools": "石制工具",
    "Supports 3 Miners": "支持3个矿工",
    "Supports 5 Builders, 2 Crafters, 1 Elder, 1 Sweeper": "支持 5 名建造者、2 名工匠、1 名长者、1 名清扫者",
    "The ongoing storm causes outdoor activities to be reduced by 50%": "持续的暴风雨导致户外活动减少50%",
    "Upgrade to a Settlement": "升级至定居点",
    "Winds from the east blow sand over the oasis": "东风吹过绿洲上的沙子",
    "Winds from the west blow sand over the oasis": "西风吹过绿洲上的沙子",
    "A small yet spacious structure, built to store large amounts of material": "一个小而宽敞的结构，用于存储大量材料",
    "A strong breeze has picked up sand from the north, casting shade over the oasis": "一阵强风卷起了北方的沙子，给绿洲投下阴影",
    "Build a Small Warehouse": "建造一个小仓库",
    "Contains space for 500 Wood, 500 Sandstone, 100 Stone Tools": "包含可容纳 500 个木材、500 个砂岩、100 个石制工具的空间",
    "Elder": "长老",
    "Logging Camp": "伐木营",
    "Lumber is chopped and refined here from the scarce trees in the area": "木材是从该地区稀有的树木中砍伐和精炼的",
    "Removes 1 foot of sand per day": "每天清除 1 英尺的沙子",
    "Set up logging operations": "设置日志记录操作",
    "Small Warehouse": "小仓库",
    "Supports 2 Loggers": "支持 2 个伐木工",
    "Sweeper": "扫地机",
    "A dust storm hangs over the oasis, blotting out the sun and bringing sand in from the west": "沙尘暴笼罩着绿洲，遮挡了阳光，并从西方带来了沙子",
    "Agriculture": "农业",
    "and further expeditions into the desert": "以及进一步的沙漠探险",
    "Animal Husbandry": "畜牧业",
    "Astrology": "占星术",
    "Better building techniques allow for larger and more spacious structures": "更好的建筑技术可以实现更大、更宽敞的结构",
    "Better construction allows for deeper and more stable mines": "更好的建设可以让矿山更深、更稳定",
    "but the sands are greedy and dry": "但沙子又贪又干",
    "Canals": "运河",
    "Careful cultivation of the fertile land around the oasis": "精心耕耘绿洲周边的肥沃土地",
    "Community": "社区",
    "Construction": "建造",
    "Demolish the Settlement": "拆除定居点",
    "Desert Farming": "沙漠农业",
    "Engineering": "工程",
    "Evaporation Pools": "蒸发池",
    "Expansion": "扩张",
    "Expeditions": "探险",
    "Exploration": "勘探",
    "it may be possible to grow more with some dedicated work": "通过一些专注的工作也许可以成长得更多",
    "it's time to look for arable land beyond the oasis valley": "是时候在绿洲山谷之外寻找可耕地了",
    "Maybe some salt can be drawn from the oasis to help with preservation": "也许可以从绿洲中提取一些盐来帮助保存",
    "Metalurgy": "冶金",
    "Mining": "矿业",
    "Raising and breeding camels will allow larger": "饲养和繁殖骆驼将允许更大的",
    "Raw ores from beneath the earth require processing to be truly useful": "来自地下的原矿石需要经过加工才能真正有用",
    "Research": "研究",
    "Ruins full of treasure dot the land, waiting only for someone to take them": "充满宝藏的废墟遍布这片土地，只等待有人来夺取它们",
    "should allow for more food for the tribe": "应该为部落提供更多食物",
    "The community is the key to survival": "社区是生存的关键",
    "The heat and insects ruin food quickly": "高温和昆虫很快就会破坏食物",
    "The land around the oasis is rich and wet,": "绿洲周围的土地肥沃湿润，",
    "The portents of the stars hold the secrets of the world": "星星的预兆蕴藏着世界的秘密",
    "The sandstorms are disruptive and dangerous, the people need protection": "沙尘暴破坏性大、危险性大，人民需要保护",
    "To leave behind a legacy of knowledge, you must write it down": "为了留下知识遗产，你必须把它写下来",
    "Unlocks Expeditions": "解锁探险",
    "Unlocks Monuments (soon™)": "解锁纪念碑（很快™）",
    "Unlocks the Basic Farm": "解锁基本农场",
    "Unlocks the Cactus Farm": "解锁仙人掌农场",
    "Unlocks the Camel Pen": "解锁骆驼围栏",
    "Unlocks the Canal": "解锁运河",
    "Unlocks the Evaporation Pool": "解锁蒸发池",
    "Unlocks the Lookout Tower": "解锁瞭望塔",
    "Unlocks the Medium Warehouse": "解锁中型仓库",
    "Unlocks the Mine": "解锁矿井",
    "Unlocks the Rudimentary Wall": "解锁简陋的墙",
    "Unlocks the Smithy": "解锁铁匠铺",
    "Unlocks the Village": "解锁村庄",
    "Upgrades Elders to Astrologists": "将长老升级为占星师",
    "While the sparse cacti don't seem to need much,": "虽然稀疏的仙人掌看似不需要太多，",
    "With the oasis becoming cluttered,": "随着绿洲变得混乱，",
    "Writing": "写作",
    "Dust and sand swirl in the air, carried by strong winds from the east": "东风吹来，灰尘和沙子在空气中旋转",
    "Contains space for 500 Wood, 500 Sandstone, 100 Salt, 300 Preserved Food, 100 Stone Tools, 500 Metal, 100 Metal Tools": "包含可容纳 500 个木材、500 个砂岩、100 个盐、300 个腌制食品、100 个石制工具、500 个金属、100 个金属工具的空间",
    "Demolish the Logging Camp": "拆除伐木场",
    "Dust and sand swirl in the air, carried by strong winds from the west": "西边的强风吹来，灰尘和沙子在空气中旋转",
    "Logger": "伐木工",
    "Supports 1 Shovelers": "支持 1 个铲车",
    "Tear down the Warehouse": "拆掉仓库",
    "Fragments of walls show this structure must have been quite large": "墙壁的碎片表明这个结构一定非常大",
    "A prickly field full of cultivated cacti": "长满栽培仙人掌的多刺田地",
    "A rudimentary wall, built to protect the settlement from the encroaching sands": "一堵简陋的墙，旨在保护定居点免受沙子的侵蚀",
    "A small cluster of ruined structures, maybe a living space?": "一小群废弃建筑，也许是一个居住空间？",
    "A strong breeze has picked up sand from the east, casting shade over the oasis": "一阵强风卷起了东边的沙子，给绿洲投下阴影",
    "Abandon the Cacti": "放弃仙人掌",
    "Archaeological Research Bonus:": "考古研究奖金：",
    "Blocks sand from reaching up to 2 tiles behind it": "阻止沙子到达其后面最多 2 格的地方",
    "Build a Rudimentary Wall": "建造一堵简陋的墙",
    "by Acamaeda": "通过阿卡梅达",
    "Cactus Farm": "仙人掌农场",
    "Farmer": "农民",
    "Made by Escapee    ": "由逃亡者制作",
    "Plant a Cactus Farm": "种植仙人掌农场",
    "Rudimentary Wall": "简陋的墙",
    "Supports 1 Farmer": "支持 1 名农民",
    "Tear down the Wall": "推倒围墙",
    "The Modding Tree": "模组树",
    "The Prestige Tree made by Jacorb and Aarex": "Jacorb 和 Aarex 制作的声望树",
    "Whoever was here before must have dug out a lot of material": "以前来过这里的人一定挖出了很多材料",
    "A dust storm hangs over the oasis, blotting out the sun and bringing sand in from the south": "沙尘暴笼罩着绿洲，遮挡了阳光，并从南方带来了沙子",
    "A dust storm hangs over the oasis, blotting out the sun and bringing sand in from the south": "沙尘暴笼罩着绿洲，遮挡了阳光，并从南方带来了沙子",
    "A large flat evaporation surface allows salt and minerals to be easily harvested from the bubbling Oasis": "大而平坦的蒸发表面使盐和矿物质可以轻松地从冒泡的绿洲中收获",
    "A simple yet vibrant field": "一个简单而充满活力的领域",
    "An expedition must take at least one month!": "一次探险至少需要一个月的时间！",
    "An expedition requires at least one person!": "一次探险至少需要一个人！",
    "Basic Farm": "基本农场",
    "Canal": "运河",
    "Dedicated channels allow water to be transported across the land": "专用渠道允许水在陆地上输送",
    "Dig a Canal": "挖一条运河",
    "Embark": "启程",
    "Evaporation Pool": "蒸发池",
    "Flatten out an Evaporation Pool": "压平蒸发池",
    "Months:": "月：",
    "Not enough Preserved Food to send, requires 300 more": "腌制食品不足，需要 300 份以上",
    "People:": "人们：",
    "Plow a Basic Farm": "耕种基本农场",
    "Supports 1 Salt Farmer": "支持 1 名盐农",
    "Supports 2 Farmers": "支持 2 名农民",
    "Unusable when buried under sand": "埋在沙子下时无法使用",
    "will require 300 dried food": "需要300干粮",
    "Years:": "年：",
    "Clear out the Farm": "清理农场",
    "Dust and sand swirl in the air, carried by strong winds from the north": "北方强风吹来，灰尘和沙子在空气中旋转",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'i': 'i',
    'ᐱ': 'ᐱ',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Year: ": "年: ",
    "Month: ": "月: ",
    "Day: ": "天: ",
    "Food: ": "食物: ",
    "Exploration: ": "探索: ",
    "Agriculture: ": "农业: ",
    "Construction: ": "建造: ",
    "Research Points: ": "研究点数: ",
    "Stone Tools: ": "石制工具: ",
    "Sandstone: ": "砂岩: ",
    "Current Dried Food: ": "当前的干制食品: ",
    "Days of Work: ": "工作天数: ",
    "In Progress: ": "进行中：",
    "Confirm New Game: ": "确认新游戏:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/day": "/天",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Currently buried under (.+) feet of sand$/, '目前被埋在 $1 英尺的沙子下面'],
    [/^Can function under (.+) feet of sand$/, '可以在 $1 英尺深的沙子下工作'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Sending (.+) people for (.+) month$/, '派遣 $1 人，持续 $2 个月'],
    [/^Not enough free people to send, requires (.+) more unemployed$/, '没有足够的空闲人口可以派出，需要再招募 $1 名未分配人员'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Production: (.+) Wood$/, '生产：$1 木头'],
    [/^Production: (.+) Food$/, '生产：$1 食物'],
    [/^Production: (.+) Stone Tools$/, '生产：$1 石制工具'],
    [/^Production: (.+) Research$/, '生产：$1 研究'],
    [/^Production: (.+) Sandstone$/, '生产：$1 砂岩'],
    [/^Wood: (.+)$/, '木头：$1'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);